### ISSUE TITLE
Multi-user connection 

### ISSUE THREAD

**Issue by OoAryanoO** [korn-sudo/Project-Fog#10]
Hi👋 Thanks for your good script . please add multi-user connection limit to openvpn
now just working for dropbear

**Comment by zeeid** [comment]
i need multi user at same port  to :(

**Comment by korn-sudo** [comment]
**Only SSH and Dropbear Ports are subject to the Multi Login User Restriction.** Why?
- Various issues and incompatibilities I've run into with OpenVPN, the limitations can't be added.
- I'm unable to debug or adjust the restriction method approach due to a time constraint.
-  I don't have a virtual private server.

_I don't have a virtual private server right now, so just keep an eye on your internet customers in:_
- Monitoring with OpenVPN ( your-ip-add:89)
- Online User (enter "menu" > "6" into your terminal)
or
You can simply convert your OpenVPN configuration to SSH format and use it.



_For the time being, I'll put this on my Project Fog priority list. We can make work on this request if I have some time and someone has a spare vps._

Thank you. ;)

**Comment by OoAryanoO** [comment]
i solved  :) now enable 2 user conection limit 👍 
how can enable cipher 128 or 256  ? by default no cipher enabled
